AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs18.x
      Events:
        KinesisEvent:
          Type: Kinesis
          Properties:
            Stream: !GetAtt Source.Arn
            StartingPosition: TRIM_HORIZON
            BatchSize: 1
            FilterCriteria:
              Filters:
                - Pattern: '{"data": {"Type": ["analytics"] }}'

  EDAFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: edaFunction.handler
      Runtime: nodejs18.x
      Events:
        KinesisEvent:
          Type: Kinesis
          Properties:
            StartingPosition: TRIM_HORIZON
            Stream: !GetAtt Source.Arn
            BatchSize: 1
            FilterCriteria:
              Filters:
                - Pattern: '{"data": {"Type": ["EDA"] }}'

  Source:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Sub ${AWS::StackName}-source
      StreamModeDetails:
        StreamMode: ON_DEMAND
